### ISSUE TITLE
Boss Bar glitching

### ISSUE THREAD

**Issue by AvaAsUsual** [UkrainenBimba/desert-scourge#6]
When summoning two worms at once, or when one is /killed, the boss bar will forever stay on your screen with no possible way to remove it, please add some sort of /function desertscourge/bossbar/clear command, thank you :)

**Comment by duncy** [comment]
Hey there, I had this issue as well, I found a solution for it.
You should be able to use the vanilla command /bossbar remove minecraft:desert_scourge_1, yours may be different but it should be obvious from the autocomplete options. :)

**Comment by AvaAsUsual** [comment]
Thank you :D
